[package]
name = "lddm_scraper"
version = "0.1.0"
authors = ["lithrel"]

[dependencies]
hyper = "0.10"
futures = "0.1.11"
tokio-core = "0.1.6"
regex = "0.2"
select = "0.3"
slug = "0.1.2"
rustc-serialize = "0.3.23"
chrono = "0.3"